<?php

$queries[] = 'CREATE TABLE IF NOT EXISTS comment(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guest VARCHAR(50) NOT NULL,
    message TEXT NOT NULL
) ENGINE=InnoDB CHARACTER SET=utf8;';